"""Application defaults — the single source of truth for all brand keys.

Every brand key has a default value, a one-line comment (used as the comment in the
YAML written by `brandx init`), and a purpose string (used in the config-reference
doc generated by `brandx docsgen`).

The structure mirrors the YAML shape: top-level scalar keys and a nested `colours`
mapping. Nested mappings are represented as plain dicts; the resolver deep-merges them
so a single override leaves the rest of the palette intact.

Usage:
    from brandx.config.defaults import DEFAULTS
    val = DEFAULTS["identity"]["name"]["value"]
"""

from typing import Any


def _key(value: Any, comment: str, purpose: str) -> dict:
    return {"value": value, "comment": comment, "purpose": purpose}


# ---------------------------------------------------------------------------
# Identity block
# ---------------------------------------------------------------------------

_IDENTITY = {
    "name": _key(
        value=None,
        comment="Your full name — leave blank to use your OS account name.",
        purpose=(
            "Displayed in the document/email letterhead and used to derive the monogram. "
            "When absent at every config layer the resolver reads the OS full name or "
            "title-cases the login username."
        ),
    ),
    "role": _key(
        value="",
        comment="Your job title or role line shown beneath your name in the letterhead.",
        purpose="Letterhead role line. Leave blank to omit the role from the letterhead.",
    ),
    "avatar": _key(
        value=None,
        comment="Path to an avatar image (PNG/JPEG). Leave blank to use the monogram.",
        purpose=(
            "Used in the letterhead when mark is set to 'avatar'. "
            "Relative paths resolve from the document's directory."
        ),
    ),
    "avatar_email": _key(
        value=None,
        comment="Path to a smaller avatar for email letterheads. Falls back to avatar.",
        purpose=(
            "Optional email-specific avatar (typically a smaller crop). "
            "When absent, the main avatar is used for both surfaces."
        ),
    ),
    "mark": _key(
        value="monogram",
        comment="Identity mark style: 'monogram' (default) or 'avatar'.",
        purpose="Selects the letterhead mark. 'monogram' shows derived initials; 'avatar' shows the image.",
    ),
}

# ---------------------------------------------------------------------------
# Colour palette (mirrors prototype brand.json, minus person-specific values)
# ---------------------------------------------------------------------------

_COLOURS = {
    "blue": _key(
        value="#1c2b39",
        comment="Primary dark colour — headings, table headers, letterhead text.",
        purpose="Used for primary heading and structural elements across both surfaces.",
    ),
    "blue_light": _key(
        value="#0d8a7d",
        comment="Secondary accent — role line, heading underlines, links.",
        purpose="Paired with 'blue' for the gradient bar and role text.",
    ),
    "accent": _key(
        value="#0d8a7d",
        comment="Accent colour — blockquote bars, active UI elements.",
        purpose="Used for accent borders on plain blockquotes and the letterhead gradient.",
    ),
    "important": _key(
        value="#b07514",
        comment="Amber tone for [!IMPORTANT] callout bars and labels.",
        purpose="Callout bar and label colour for the IMPORTANT alert type.",
    ),
    "grey_900": _key(
        value="#1f2933",
        comment="Near-black body text.",
        purpose="Primary body text colour on both surfaces.",
    ),
    "grey_700": _key(
        value="#46535f",
        comment="Secondary body text — callout bodies, blockquote prose.",
        purpose="Used inside callouts and blockquotes where a slightly lighter tone aids hierarchy.",
    ),
    "grey_500": _key(
        value="#7c8893",
        comment="Muted text — dates, captions, footer.",
        purpose="Date and footer text in the letterhead.",
    ),
    "grey_200": _key(
        value="#e2e8ec",
        comment="Divider and border colour.",
        purpose="Table row dividers, code-block borders, section rules.",
    ),
    "grey_50": _key(
        value="#f4f7f8",
        comment="Subtle surface background — code blocks, alternate table rows.",
        purpose="Alternate table row fill and code-block background on the document surface.",
    ),
    "rag_green_bg": _key(
        value="#e8f5ed",
        comment="Background fill for [!TIP] and RAG-green cells.",
        purpose="Alert background — TIP callout and green RAG status cells.",
    ),
    "rag_green_text": _key(
        value="#2a7f4f",
        comment="Text/bar colour for [!TIP] and RAG-green cells.",
        purpose="Alert label and bar colour for TIP callouts.",
    ),
    "rag_amber_bg": _key(
        value="#fdf3e3",
        comment="Background fill for [!WARNING] and RAG-amber cells.",
        purpose="Alert background — WARNING callout and amber RAG status cells.",
    ),
    "rag_amber_text": _key(
        value="#b07514",
        comment="Text/bar colour for [!WARNING] and RAG-amber cells.",
        purpose="Alert label and bar colour for WARNING callouts.",
    ),
    "rag_red_bg": _key(
        value="#fce8e8",
        comment="Background fill for [!CAUTION] and RAG-red cells.",
        purpose="Alert background — CAUTION callout and red RAG status cells.",
    ),
    "rag_red_text": _key(
        value="#b33a3a",
        comment="Text/bar colour for [!CAUTION] and RAG-red cells.",
        purpose="Alert label and bar colour for CAUTION callouts.",
    ),
    "note_bg_html": _key(
        value="#e6f4f2",
        comment="Background fill for [!NOTE] on the document surface.",
        purpose="NOTE callout background on the document renderer.",
    ),
    "note_bg_email": _key(
        value="#e6f4f2",
        comment="Background fill for [!NOTE] on the email surface.",
        purpose="NOTE callout background on the email renderer. May differ from note_bg_html.",
    ),
    "important_bg_html": _key(
        value="#fdf3e3",
        comment="Background fill for [!IMPORTANT] on the document surface.",
        purpose="IMPORTANT callout background on the document renderer.",
    ),
    "important_bg_email": _key(
        value="#fdf3e3",
        comment="Background fill for [!IMPORTANT] on the email surface.",
        purpose="IMPORTANT callout background on the email renderer.",
    ),
    "table_hover": _key(
        value="#e9f3f1",
        comment="Table row hover fill (document only; emails ignore :hover).",
        purpose="Hover state for table rows on the document surface.",
    ),
}

# ---------------------------------------------------------------------------
# Typography block
# ---------------------------------------------------------------------------

_FONTS = {
    "family": _key(
        value="'Inter', -apple-system, 'Segoe UI', Arial, sans-serif",
        comment="CSS font-family stack for the document surface.",
        purpose="Applied via CSS variable on the document renderer.",
    ),
    "family_email": _key(
        value="'Inter', 'Segoe UI', Arial, Helvetica, sans-serif",
        comment="CSS font-family stack for the email surface (web-safe only).",
        purpose=(
            "Inline-styled on every element in the email renderer. "
            "Email clients cannot load web fonts; this stack relies on system fonts."
        ),
    ),
    "google_url": _key(
        value="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap",
        comment="Google Fonts URL for the document surface web font. Set to empty to skip.",
        purpose=(
            "Loaded via <link> in the document renderer. "
            "Not used in email; the email stack is web-safe only."
        ),
    ),
}

# ---------------------------------------------------------------------------
# Date and locale
# ---------------------------------------------------------------------------

_DATE = {
    "format": _key(
        value="long-british",
        comment=(
            "Date display format. Named formats: 'long-british' (8 April 2026), "
            "'iso' (2026-04-08), 'us' (April 8, 2026), 'eu' (08.04.2026). "
            "Or a strftime pattern, e.g. '%%d/%%m/%%Y'."
        ),
        purpose="Controls how the document/email date is rendered in the letterhead.",
    ),
}

# ---------------------------------------------------------------------------
# Root DEFAULTS mapping
# ---------------------------------------------------------------------------
# Nested sub-mappings (colours, fonts, date, identity) keep the same dot-separated
# override grammar as the flat keys. The resolver deep-merges nested dicts so that
# a partial palette override leaves the rest intact.

DEFAULTS: dict = {
    "identity": _IDENTITY,
    "colours": _COLOURS,
    "fonts": _FONTS,
    "date": _DATE,
}


def flat_defaults() -> dict[str, Any]:
    """Return a flat {key: value} dict of all defaults (nested keys dot-joined).

    Used by the resolver to seed the base config layer.
    """
    result: dict[str, Any] = {}

    def _walk(node: dict, prefix: str) -> None:
        for k, v in node.items():
            path = f"{prefix}.{k}" if prefix else k
            if isinstance(v, dict) and "value" in v and "comment" in v:
                result[path] = v["value"]
            elif isinstance(v, dict):
                _walk(v, path)

    _walk(DEFAULTS, "")
    return result


def nested_defaults() -> dict:
    """Return a nested {key: value} dict of all defaults.

    The shape mirrors the YAML a user would write: nested mappings for
    colours, fonts, date, and identity, with plain values (not the
    comment/purpose dicts).
    """

    def _extract(node: dict) -> Any:
        if isinstance(node, dict) and "value" in node and "comment" in node:
            return node["value"]
        if isinstance(node, dict):
            return {k: _extract(v) for k, v in node.items()}
        return node

    return {k: _extract(v) for k, v in DEFAULTS.items()}
