"""brandx init command — scaffold a starter brand config from the defaults source.

Serialises the application defaults to a fully-commented YAML file at the home
config location, creating the parent directory if needed. Refuses to overwrite
an existing file unless --force is passed.

The generated file shows every key with its default value and its one-line
comment, so a user can edit it without consulting any other documentation.

Usage (via CLI):
    brandx init           # writes to XDG home location
    brandx init --force   # overwrites an existing config

Programmatic:
    from brandx.initcmd import run_init
    run_init(force=False)
"""

import sys
from pathlib import Path

from brandx.config.defaults import DEFAULTS
from brandx.config.discovery import default_config_path


# ---------------------------------------------------------------------------
# YAML serialisation with comments
# ---------------------------------------------------------------------------

def _serialize_defaults_to_yaml(node: dict, indent: int = 0) -> list[str]:
    """Recursively serialise DEFAULTS to YAML lines with inline comments.

    Leaf nodes (dicts with 'value' and 'comment') emit:
        key: <value>  # <comment>

    Branch nodes emit:
        key:
          ...children...
    """
    lines: list[str] = []
    pad = "  " * indent

    for key, entry in node.items():
        if isinstance(entry, dict) and "value" in entry and "comment" in entry:
            value = entry["value"]
            comment = entry["comment"]
            yaml_value = _to_yaml_scalar(value)
            lines.append(f"{pad}{key}: {yaml_value}  # {comment}")
        elif isinstance(entry, dict):
            lines.append(f"{pad}{key}:")
            lines.extend(_serialize_defaults_to_yaml(entry, indent + 1))
        else:
            lines.append(f"{pad}{key}: {entry}")

    return lines


def _to_yaml_scalar(value) -> str:
    """Convert a Python scalar to a YAML-safe string representation."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if any(c in text for c in ":#{}[]|>&*?!,@`\n"):
        escaped = text.replace('"', '\\"')
        return f'"{escaped}"'
    if text == "" or text.lower() in ("true", "false", "null", "yes", "no", "on", "off"):
        return f'"{text}"'
    return text


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_init_yaml() -> str:
    """Generate the fully-commented starter config YAML string from DEFAULTS.

    Returns a YAML string suitable for writing to the home config file.
    """
    lines = [
        "# brandx brand configuration",
        "# Generated by `brandx init`. Edit the values below to customise your brand.",
        "# Run `brandx init --force` to regenerate this file.",
        "#",
        "",
    ]
    lines.extend(_serialize_defaults_to_yaml(DEFAULTS))
    lines.append("")
    return "\n".join(lines)


def run_init(force: bool = False, target_path: Path | None = None) -> Path:
    """Write the starter brand config to the home location.

    Args:
        force: When True, overwrite an existing config. When False (default),
               raise SystemExit if the target already exists.
        target_path: Override the default config path (for testing).

    Returns:
        The Path where the config was written.

    Raises:
        SystemExit: If the target exists and force is False.
    """
    path = target_path or default_config_path()

    if path.exists() and not force:
        sys.exit(
            f"Error: a brand config already exists at {path}.\n"
            f"Run `brandx init --force` to overwrite it."
        )

    path.parent.mkdir(parents=True, exist_ok=True)
    yaml_content = generate_init_yaml()
    path.write_text(yaml_content, encoding="utf-8")

    print(f"Written: {path}", file=sys.stderr)
    return path
